# Generated by Django 6.0.3 on 2026-05-25 21:29

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tableitem_preco'),
        ('home', '0005_tableitem'),
    ]

    operations = []