# Generated by Django 6.0.3 on 2026-05-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableitem',
            name='preco',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
